CREATE DATABASE IF NOT EXISTS PARSER;

CREATE TABLE IF NOT EXISTS PARSER.LOG  (
    ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    REQUEST_DATE datetime(3) NOT NULL,
    IP VARCHAR(20) NOT NULL,
    REQUEST VARCHAR(255) NOT NULL,
    STATUS VARCHAR(5) NOT NULL,
    USER_AGENT VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS PARSER.BLOCKED_IP  (
    ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    IP VARCHAR(20) NOT NULL,
    COMMENT VARCHAR(255) NOT NULL
);

#SQL queries are in src/main/resources/spring/job/spring-parser.xml
select * from parser.log where ip='192.168.162.248';